/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteHrArgs } from "./DeleteHrArgs";
import { HrCountArgs } from "./HrCountArgs";
import { HrFindManyArgs } from "./HrFindManyArgs";
import { HrFindUniqueArgs } from "./HrFindUniqueArgs";
import { Hr } from "./Hr";
import { HrService } from "../hr.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Hr)
export class HrResolverBase {
  constructor(
    protected readonly service: HrService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Hr",
    action: "read",
    possession: "any",
  })
  async _hrsMeta(@graphql.Args() args: HrCountArgs): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Hr])
  @nestAccessControl.UseRoles({
    resource: "Hr",
    action: "read",
    possession: "any",
  })
  async hrs(@graphql.Args() args: HrFindManyArgs): Promise<Hr[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Hr, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Hr",
    action: "read",
    possession: "own",
  })
  async hr(@graphql.Args() args: HrFindUniqueArgs): Promise<Hr | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Hr)
  @nestAccessControl.UseRoles({
    resource: "Hr",
    action: "delete",
    possession: "any",
  })
  async deleteHr(@graphql.Args() args: DeleteHrArgs): Promise<Hr | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
